services:

  master:
    build:
      context: .
      dockerfile: dockerfile.master
    environment:
      - CHUNK_SERVICE_URLS=http://chunk1:8001,http://chunk2:8001,http://chunk3:8001,http://chunk4:8001,http://chunk5:8001
    ports:
      - 8000:8000

  chunk1:
    build:
      context: .
      dockerfile: dockerfile.chunk
    ports:
      - 8001:8001

  chunk2:
    build:
      context: .
      dockerfile: dockerfile.chunk
    ports:
      - 8002:8001

  chunk3:
    build:
      context: .
      dockerfile: dockerfile.chunk
    ports:
      - 8003:8001

  chunk4:
    build:
      context: .
      dockerfile: dockerfile.chunk
    ports:
      - 8004:8001

  chunk5:
    build:
      context: .
      dockerfile: dockerfile.chunk
    ports:
      - 8005:8001