FROM golang:1.20-alpine AS builder
WORKDIR /grotto
COPY . .
RUN go mod download
RUN go build -o chunk cmd/chunk/main.go

FROM alpine:latest
WORKDIR /grotto
COPY --from=builder /grotto/chunk .
EXPOSE 8001
CMD ["./chunk"]